### ISSUE TITLE
Repo not created

### ISSUE THREAD

**Issue by rth** [conda-forge/scikit-learn-extra-feedstock#1]
Looks like the creation of repo failed due to Github API rate limits in `staged-recipes`. Can someone please restart Travis CI there (if that's the solution). Thanks!

**Log**
```
python .travis_scripts/create_feedstocks.py

GitHub API Rate Limit Info:

---------------------------

token:  GH_DRONE_TOKEN

Currently remaining 4997 out of 5000.

Will reset in 0:27:42.290495.

GitHub API Rate Limit Info:

---------------------------

token:  GH_TOKEN

Currently remaining 0 out of 5000.

Will reset in 0:23:21.100179.

Calculating the recipes which need to be turned into feedstocks.

No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11

Making feedstock for scikit-learn-extra

No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11

Initialized empty Git repository in /tmp/tmprbrctqvy__feedstocks/scikit-learn-extra-feedstock/.git/

[master (root-commit) a779065] Initial feedstock commit with conda-smithy 3.6.15.

 2 files changed, 62 insertions(+)

 create mode 100644 conda-forge.yml

 create mode 100644 recipe/meta.yaml

Repository created, please edit conda-forge.yml to configure the upload channels

and afterwards call 'conda smithy register-github'

GitHub API Rate Limit Info:
---------------------------
token:  GH_DRONE_TOKEN
Currently remaining 4997 out of 5000.
Will reset in 0:27:40.156072.
Traceback (most recent call last):
  File ".travis_scripts/create_feedstocks.py", line 202, in <module>
    if repo_exists(gh, 'conda-forge', name + '-feedstock'):
  File ".travis_scripts/create_feedstocks.py", line 61, in repo_exists
    org = gh.get_organization(organization)
  File "/home/travis/miniconda/lib/python3.7/site-packages/github/MainClass.py", line 263, in get_organization
    "/orgs/" + login
  File "/home/travis/miniconda/lib/python3.7/site-packages/github/Requester.py", line 275, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/home/travis/miniconda/lib/python3.7/site-packages/github/Requester.py", line 286, in __check

    raise self.__createException(status, responseHeaders, output)
github.GithubException.RateLimitExceededException: 403 {'message': 'API rate limit exceeded for user ID 37169284.', 'documentation_url': 'https://developer.github.com/v3/#rate-limiting'}

+++set +x

+++python .travis_scripts/trigger_travis_build.py conda-forge/staged-recipes
b'access denied'
Traceback (most recent call last):
  File ".travis_scripts/trigger_travis_build.py", line 54, in <module>
    sys.exit(main(sys.argv))
  File ".travis_scripts/trigger_travis_build.py", line 47, in main
    rebuild_travis(args.slug)
  File ".travis_scripts/trigger_travis_build.py", line 38, in rebuild_travis
    response.raise_for_status()
  File "/home/travis/miniconda/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.travis-ci.com/repo/conda-forge%2Fstaged-recipes/requests
```

**Comment by rth** [comment]
Someone fixed it. Thanks!
